### PR TITLE
Make Variables behave as Symbols

### PR DESCRIPTION
**Pull request by jirikuncar**

### CODE REVIEW

**Comment by schymans** [comment]
Apparently, this broke test_units() in test_equations.py.

**Comment by schymans** [comment]
Note also that the added test is satisfied using the current master, probably due to a change upstream, in sympy:
```
def test_integral():
    """Test that variables behave as symbols."""
    from sympy import integrate

    assert demo_g in demo_fall.free_symbols
    assert demo_g * demo_fall.definition.t**S(3) / S(6) == integrate(
        demo_fall.rhs, demo_fall.definition.t)
```

**Comment by jirikuncar** [comment]
So maybe we can just add the test alone.

**Comment by schymans** [comment]
The thing is, they probably should not behave as symbols. I finally understood what is meant by the comment that symbols in an expression could balance non-matching units. For example, one could formulate an empirical equation where the units of the proportionality constant are not known a priori. One could use a symbol for the constant, then solve the equation for the symbol, substitute the units of all variables and in this way deduce the appropriate units of the constant. So, all we need to test for is that integrate() works if the integration variable is a quantity. This was the original test. We could add additional tests for other methods, one-by-one. No need to treat a quantity as a free_symbol in general.

**Review by schymans — CHANGES_REQUESTED** [review]
This test would suffice:
```
def test_integral():
    """Test that variables behave as symbols."""
    from sympy import integrate
    assert demo_g * demo_fall.definition.t**S(3) / S(6) == integrate(
        demo_fall.rhs, demo_fall.definition.t)
```

**Review by schymans — DISMISSED** [review]
Just needs a minor fix:
/home/travis/build/environmentalscience/essm/tests/test_equations.py:59:1: W293 blank line contains whitespace

**Review by schymans — APPROVED** [review]
All test passed now, thanks, Jiri!

**Comment by schymans** [comment]
OK, variables do not behave as symbols, but this is probably not needed after all. Most importantly, integrate() with variables works now.

**Pull request merged**
